### PR TITLE
feat(schedule): Schedule Page

### LINKED ISSUE #56: Page: Schedule
/schedule

### PR DESCRIPTION
**Pull request by milhamm**
Closes #56

### CODE REVIEW

**Comment by dmaharika** [comment]
Looks Good, kalau ada improvement tambahan memungkinkan ga ya?
Kaya filter based on Level atau Tags.

**Review by dmaharika — COMMENTED** [review]
Can we add filtering?

**Comment by milhamm** [comment]
@dmaharika sure we can add those improvements later on

**Comment by dmaharika** [comment]
Nice then, for now it's looking good. But are we gonna deploy it now? Since there's still no fixed schedule for now.

**Comment by milhamm** [comment]
We have 2 options

First, we can leave it open here until the fixed schedule is determined 
The second option is displaying an empty page (TBD) changing it later and merging only the code/components. 

What do you think?
@dmaharika

**Comment by dmaharika** [comment]
Ah, so the second option is when we go to the schedule page it shows TBA instead of 404 page?

**Comment by milhamm** [comment]
Correct @dmaharika

**Comment by dmaharika** [comment]
We can try the second option then

**Comment by milhamm** [comment]
Updated, merging @dmaharika

**Pull request merged**
