### PR TITLE
feat(speakers): Speakers Page

### LINKED ISSUE #58: Page: Speakers

### PR DESCRIPTION
**Pull request by milhamm**
Sliced the Speakers page based on Figma design

Closes #58

### CODE REVIEW

**Comment by dmaharika** [comment]
Pas di responsive sepertinya perlu dicek lagi. Kalau size mobile device masih oke, tapi pas size tab/ipad keliatannya kurang pas di frame fotonya.

**Comment by jeeehaan** [comment]
I feel that the gap between the speaker card is quite tight, what if we increase the gap mas @milhamm?

**Comment by milhamm** [comment]
Will do @dmaharika @jeeehaan

**Comment by dmaharika** [comment]
Lgtm!

**Review by dmaharika — APPROVED** [review]

**Pull request merged**
