### PR TITLE
Update coc._index.tsx

### PR DESCRIPTION
**Pull request by dmaharika**
Update the year to 2023 and add how to report an incident

### CODE REVIEW

**Comment by milhamm** [comment]
Screenshot_20230903_054446_Chrome

Is this backslash intentional? @dmaharika

**Comment by dmaharika** [comment]
Typo, udah aku benerin di commit terakhir

**Comment by dmaharika** [comment]
Just realized warna bgnya ungu tapi garisnya oren. So dumb of me.

**Comment by milhamm** [comment]
Nah paling BG dan border juga. Sisanya looks good mas @dmaharika

**Review by milhamm — APPROVED** [review]

**Comment by dmaharika** [comment]
Updateng the border. Thanks for the review!

**Pull request merged**
