### PR TITLE
feat(migration): add new migration table

### PR DESCRIPTION
**Pull request by vhermawan**
Closes https://github.com/bandungpy/pycon.id/issues/38

Add new migration for schema prisma.

### CODE REVIEW

**Review by mhaidarhanif — APPROVED** [review]
Quite good, but now I'm refining it.

**Comment by mhaidarhanif** [comment]
@bandungpy/backend Please check the improved schema

**Comment by mhaidarhanif** [comment]
Let's wait until 1 of @bandungpy/backend team approved because the field name changes will affect several things.

**Comment by fadoilulmun-im** [comment]
I think it is in accordance with the meeting results

**Comment by aldamr01** [comment]
Request, please add `uuid` attribute in User model, as a unique id for Backend need instead of using `id` field, which is too short and predictable. 

CC: @vhermawan @mhaidarhanif

**Review by aldamr01 — APPROVED** [review]
LGTM

**Comment by vhermawan** [comment]
i just fixing cpnflict in package json mas @mhaidarhanif, this is should be fine and we can merge this PR

**Pull request merged**
